### ISSUE TITLE
Responsive design (skubu) - rezultatai prisegtame komentare

### ISSUE THREAD

**Issue by VytautasValutis** [front-end-by-rimantas/42-grupe-portfolio-agar#17]
- ribu nustatymas

**Comment by VytautasValutis** [comment]
Skirtingos  web dalys siaurinant  ekrana reaguoja _SKIRTINGAI_. Reikes responsive design atlikinet individualiai.
Startas: desktop pradetas nuo 1200px

1- Navbar
  - 990 px virsuje kaireje dingsta meniu
  - 570 px desniajeme kampe dingsta meniu ir socialiniai linkai - lieka pajieskos piktograma. Logo centruojasi.
2- banner
  - 1020 px desines puses tekstas pasislenks zemyn ir uzima visa ploti
  -  990 px virsuje kaireje dingsta meniu
  - 570 px desniajeme kampe dingsta meniu ir socialiniai linkai - lieka pajieskos piktograma.  
3- About
  - 1190 px is 6 lieka 5 logo
  - 900 px is 5 lieka 4 logo
  - 700 px is 4 lieka 3 logo
  - 570 px is 3 lieka  2 logo
4- Services
  - 1190 px eileje lieka 3 logo
  -  990 px virsuje kaireje dingsta meniu (kartojasi per visa dizaina)
  - eileje lieka 2 logo
  - 760 px eileje lieka 1 logo
5- Why us
  - 1020 px tekstas ir linijos palenda po nuotraukomis
6- Working process
  - 1400 px atsiranda lektos rodykles nuo vieno paveiksliuko prie kito
  - 990 px is 4 paveiksliuku eileje lieka 2
  - 570 px is 2 paveiksliuku eileje lieka 1
7- Our project
  - 990 px 6 meniu elementas palenda po eilute is 5
  - 700 px  meniu isdestymas 4 + 2
  - paveiksliukai rikiuojasi stulpeliu
8- Numbers - EZ
  - 700 px skaiciai rikiuojasi 2 + 2
9- Reviews - Same
  - 990 px karusele keiciasi is 3 eluteje i 1 
10- Contact - EZ
11- Blogs - Same
  - 990 px blogai 3 --> 2
  - 700 px blogai 2 --> 1
12- Subscribe - EZ
13- Footer
  - 1200 px logo tekstas ir socialiniai linkai keliasi i virsu
  - 770 px vertikalus link meniu, help meniu ir kontaktai rikiuojasi stulpeliu 
14- Responsive design

**Comment by MonikaJaraite** [comment]
Matau siokiu tokiu sutapimu:
- Mazdaug ties 1200px vienas pokytis per about, services ir footer (tiksliau, 1190px ir 1200ps, bet turbut galima apjungti i 1200px)
- 990px navbar, banner, (900px about irgi prijungti?), services, working process, our project, reviews, blogs
- 700px about, (760px services prijungti?), our project, numbers, blogs, (770px footer prijungti?) - gal galima rasti koki "aukso viduriuka", kad graziai viskas keistusi - pvz, 730px?
- 570px navbar, about, working process
Gal siuos galima paimti kaip standartinius, o paskui kitus px kaip individualius?

**Comment by VytautasValutis** [comment]
Jokiu problemu, bet manau, kad masiskai bendru laiautu visiems gyvenimo atvejams nepavyks parasyti.
As cia pabandziau suvesti statistika.
